### PR TITLE
Added a python program

### PR DESCRIPTION
**Pull request by charu210703**

### CODE REVIEW

**Comment by Mewwaa** [comment]
Sorry, I believe that merging this contribution might result in excluding this repository, so thanks for participation, but I'm closing this PR.
Have a good day.

**Comment by charu210703** [comment]
Actually I am very new to this. May I know why it may result in excluding?

**Comment by Mewwaa** [comment]
Sure, I'm participating in Hacktoberfest since last year and I contributed to a lot of easy looking repositories, but they always got excluded because of not valuable projects, like removing spaces from sentences or showing how algorithms work, etc.

**Comment by charu210703** [comment]
I have a Kaprekar constant python program, can I add it? or do you have anything in mind I can work on?

**Pull request closed without merging**
